version: "3.9"
services:
  laravel:
    build:
      dockerfile: ./docker/laravel/Dockerfile
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_NAME=${APP_NAME:-Laravel}
      - APP_ENV=${APP_ENV:-local}
      - APP_URL=${APP_URL:-http://localhost}
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABAS:-laravel}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - ./sources:/data
    depends_on:
      - newrelic-php-daemon
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      - APP_HOST=${APP_HOST:-laravel}
      - WEB_PORT=${APP_HOST:-80}
      - WEB_HOST=${APP_HOST:-localhost}
    ports:
      - 8080:80
    volumes:
      - ./sources/public:/data/public
    depends_on:
      - laravel
  db:
    build:
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/db-store:/var/lib/mysql
  newrelic-php-daemon:
    image: newrelic/php-daemon
    platform: linux/amd64   